from dotenv import load_dotenv

import os

load_dotenv()

# Angel One

ANGEL_API_KEY = os.getenv("ANGEL_API_KEY")

ANGEL_CLIENT_ID = os.getenv("ANGEL_CLIENT_ID")

ANGEL_PASSWORD = os.getenv("ANGEL_PASSWORD")

ANGEL_TOTP_SECRET = os.getenv("ANGEL_TOTP_SECRET")

# GEMINI

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Telegram

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

# Database

DATABASE_URL = os.getenv("DATABASE_URL")

# App

APP_ENV = os.getenv("APP_ENV", "development")

# Nifty 50 stocks list

NIFTY_50_SYMBOLS = [

    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",

    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",

    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "TITAN",

    "SUNPHARMA", "ULTRACEMCO", "BAJFINANCE", "WIPRO", "NESTLEIND",

    "POWERGRID", "NTPC", "TECHM", "TATAMOTORS", "HCLTECH",

    "BAJAJFINSV", "ONGC", "JSWSTEEL", "TATASTEEL", "ADANIENT",

    "ADANIPORTS", "COALINDIA", "DIVISLAB", "DRREDDY", "EICHERMOT",

    "GRASIM", "HEROMOTOCO", "HINDALCO", "INDUSINDBK", "M&M",

    "BRITANNIA", "CIPLA", "APOLLOHOSP", "BAJAJ-AUTO", "BPCL",

    "TATACONSUM", "UPL", "VEDL", "SHREECEM", "SBILIFE"

]

# Trading config

SWING_SCAN_TIME = "08:30"

INTRADAY_START_TIME = "09:15"

INTRADAY_END_TIME = "11:00"

EOD_SUMMARY_TIME = "15:20"

# Scoring thresholds

MIN_SCORE_TO_ALERT = 7.0

MIN_RISK_REWARD = 2.0

# Capital config

TOTAL_CAPITAL = 25000

INTRADAY_CAPITAL = 10000

SWING_CAPITAL = 15000

MAX_RISK_PER_INTRADAY_TRADE = 500

MAX_DAILY_LOSS = 1000
